import { PowerA3 } from "./funcsion1.js";
console.log(PowerA3());
import { PowerA234 } from "./function2.js";
console.log(PowerA234());
import { MEAN } from "./function3.js";
console.log(MEAN());
import { Triangle } from "./function4.js";
console.log(Triangle());
import { ReactPs } from "./function5.js";
console.log(ReactPs() );
import { DigitCountSum } from "./function6.js";
console.log(DigitCountSum());
import { teskarison } from "./function7.js";
console.log(teskarison());
import { numstring } from "./function8.js";
console.log(numstring());
import { taqqoslash } from "./function9.js";
console.log(taqqoslash());
import { swip } from "./function10.js";
console.log(swip());